name: Run Tests

# Trigger on all push and pull request events
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node_version: '20'
      use_npm_cache: true
      run_build: true
      build_command: npm run build
      run_codecov: true
      codecov_files: ./coverage/star-wars-angular-app/lcov.info
      codecov_flags: unittests
      codecov_name: codecov-umbrella
    secrets: inherit
